### ISSUE TITLE
BarcelonaJS January Newsletter

### ISSUE THREAD

**Issue by PatrickHeneise** [BarcelonaJS/feedback#1]
Every month we send out a newsletter or two to all our members. If you have something to add or share that you want to get out there - put it here. 

- Keep it JavaScript related (articles, javascript in the wild, blog post links.. stories, jokes, projects,.)
- Keep it London related. (SF is cool y'all but we are here.)
- Keep it community related. (That's about you and the people around you using node.js)

Oh, and it's not a jobs board, so don't even try. Jobs have a [separate repo](https://github.com/BarcelonaJS/jobs).

**Comment by dasilvacontin** [comment]
> London

Did you mean Barcelona?

**Comment by PatrickHeneise** [comment]
ofc
