### ISSUE TITLE
Visuals for BarcelonaJS recordings

### ISSUE THREAD

**Issue by PatrickHeneise** [BarcelonaJS/feedback#3]
Our recordings from BarcelonaJS and NodeConf will need an intro and outro screen. Anyone up for the challenge?

**Comment by cantabrian** [comment]
here, for download from wetransfer, a sample of intros and outs.
http://we.tl/nSMTlQevQ5

**Comment by PatrickHeneise** [comment]
@cantabrian doesn't work unfortunately. Can you fork this repo or create a repo with the files in them please?
