### ISSUE TITLE
New BarcelonaJS Organisers

### ISSUE THREAD

**Issue by PatrickHeneise** [BarcelonaJS/feedback#8]
# Job Description
- Find & schedule speakers
- Schedule the event with the venue
- Update website, meetup.com, ...
- Promote the event on social media
- Monthly newsletter with the event, jobs, cool JS stuff in the city
- Interact with chapters - @BarcelonaJS/nodejs @BarcelonaJS/adabcnjs @BarcelonaJS/reactjs
- Schedule additional events (jsCodeRetreat, BeerJS, ...)

Takes approx. 1 hour per week for 2-3 organisers.

**Comment by ifraixedes** [comment]
I think that we should update the website mentioning the current status and pointing to this issue for joining to the discussion.

**Comment by Gpx** [comment]
I would like to help out with this

**Comment by ifraixedes** [comment]
@gpx Help is always very much appreciated, but what what's currently needed are 2 or 3 people to commit to be the organizers of the community.

Could you specify if you would be happy to be one of those or you can provide some help to the ones who eventually will take the role?

**Comment by Gpx** [comment]
@ifraixedes sorry for being unclear; I would like to become one of the organizers. I enjoy to be part of the development community here in Barcelona, and I would be happy to organize BarcelonaJS and all the other events around it.

I want to point out that I have no previous experience doing this, so the only thing I can offer is my time and goodwill. If you think that it's enough then count me in

**Comment by ifraixedes** [comment]
@Gpx personally, I think that's required and enough to be an organizer.
People with experience will be happy to tell you about it

**Comment by Gpx** [comment]
@ifraixedes that sounds great. Just let me know what's the process for applying.

**Comment by arol** [comment]
Hi everyone! I'm a co-founder of [Codeworks](https://codeworks.me/), a JS coding bootcamp in Barcelona. Is there a chance for the bootcamp to count as an organizer. I mean, is it ok for you if a company involves in it? If it's so, we would like to apply to the job as well! 😄

**Comment by ifraixedes** [comment]
Thinking out loud, I wouldn't see any issue if
- There's a person or some of them who care about, because having a general contact to a Juridic organization may end up to slow down even more the decisions and actions to perform.
- The vote count for the organization is just one, as any individual.
- There isn't any profit, branding, advertisement or any other favoritism for the company for the company only for being part of the organization than the same one that any individual organizer has.

At the end, what all of these mean, is that there isn't any special treatment for the organization than any other individual organizer has and all the organizers acting as the organization counts as an individual organizer.

The founders will have more to say here, I guess.

**Comment by PatrickHeneise** [comment]
BarcelonaJS is a community run by individuals without commercial interests. I see this as a conflict with code schools. There's certain events (NodeSchool, jsCodeRetreat, ...) which make sense to run with/at a code school, but the regular event and community should remain free of advertisement, profit and branding.

**Comment by arol** [comment]
I completely understand, it makes sense! I had to try.

We just started our first course in Barcelona, but we want to become part of this community eventually. Let's talk in the future if we can help you with something, then.

**Comment by PatrickHeneise** [comment]
@arol jsCodeRetreat is still free for taking, if you're interested. It's a one day "improve your code" event, http://jscoderetreat.com/howitworks.html

**Comment by Gpx** [comment]
Guys, any update on when should we meet?

**Comment by PatrickHeneise** [comment]
25/26.11. would work

**Comment by Gpx** [comment]
I'm at Reactive Conf on those days. Is it not possible this week?

**Comment by PatrickHeneise** [comment]
I'm at NodeConf EU. 22nd in the late afternoon could work?

**Comment by ifraixedes** [comment]
Sorry guys, impossible to me this month to help you out, I've just moved yesterday to my new home and I have to sort out lot of things.

**Comment by Gpx** [comment]
These are the days I have free. Let me know if any is good for you
19, 20, 24, 31, 1, 2, 3

**Comment by masylum** [comment]
I can help organizing the event too if you need more people. When are you meeting in the end? I have this week quite available.

**Comment by PatrickHeneise** [comment]
@dgil are you available / interested to continue? I'm out of town until 3.11., how about Saturday, 5.11. in the afternoon?

**Comment by sindrehopland** [comment]
@PatrickHeneise I'm up for it, we could do it at itnig and through our team. We have a very well-functioning event team set up already!

**Comment by Gpx** [comment]
From the 8th I'm always free. I can try to find some time on the 5th but I can't guarantee

**Comment by ifraixedes** [comment]
From 8.11 I should be able to find a spot too.

**Comment by PatrickHeneise** [comment]
Let's do 8th then, no problem. @masylum @dgil ?

**Comment by masylum** [comment]
Works for me!

**Comment by Gpx** [comment]
Time/place?

**Comment by PatrickHeneise** [comment]
My fav is Black Lab near Barceloneta, quiet during the week and good beer :P. But open to suggestions.

**Comment by Gpx** [comment]
This one? https://goo.gl/maps/xqr2ZvE4Jun

**Comment by ifraixedes** [comment]
@Gpx yes, that one is the one that @PatrickHeneise get a referral commission 😝 😉

**Comment by PatrickHeneise** [comment]
haha not really, just decent beer and good space to meet ;)

**Comment by PatrickHeneise** [comment]
(I should ask for a commission!!)

**Comment by dgil** [comment]
Sorry guys, I missed this thread. Can I help somehow?

**Comment by PatrickHeneise** [comment]
@dgil if you're interested to continue, we'll meed Nov 8 at Black Lab near Barceloneta with everyone else who wants to continue to run BarcelonaJS. 

Time, I'd propose 7pm?

**Comment by PatrickHeneise** [comment]
@ifraixedes @Gpx @masylum @dgil @arol how about tomorrow?

**Comment by Gpx** [comment]
I'm in

**Comment by lmuntaner** [comment]
Hey! I might be interested as well. I am coming if that's ok,

**Comment by ifraixedes** [comment]
I have a high probability to come, but around 8pm. Sorry for not being able to join at 7pm.

@Imuntaner of course that's OK

**Comment by motanelu** [comment]
Can we make it 8pm?

**Comment by lmuntaner** [comment]
I will have to leave around 8:45pm, but that's ok for me as well

**Comment by ifraixedes** [comment]
@motanelu I guess that the most of us, we'll be around until 8.30pm, at least.

**Comment by dgil** [comment]
I'm in too!
